title: George Washtol
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog where Iâ€™ll be sharing all my thoughts 
  in English and Spanish about different topics such as personal 
  growing, personal branding, good habits, English learning, 
  tech stuffs, digital minimalism, pragmatic topics 
  and counter intuitive thinking.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://georgewashtol.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jorge Toledo
author-img: jorge-toledo.jpeg
about-author: Este es mi blog personal donde comparto algunos de mis pensamientos y conocimientos. # add description
social-instagram: georgewashtol
social-github: georgewashtol
social-linkedin: georgewashtol
social-email: georgewashtol@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]